user-name: Thien
chat_log_directory: ../data/raw-history/
dataset:
  file: ../dataset/chat-set.pt
  num_candidates: 3
  max_history: 4
  max_message_length: 128
train:
  batch_size: 4
  num_epochs: 3
  train_dataset_proportion: 0.95
  learning_rate: 6.25e-5
  lm_coeff: 2.0
  mc_coeff: 1.0
  max_norm: 1
eval:
  model_path: checkpoints/model-20-12-22-13-00-17-iter20469.pt
  temperature: 0.7
  top_p: 0.9
