user-name: Thien
chat_log_directory: ../data/raw-history/
dataset:
  file: ../dataset/chat-set.pt
  num_candidates: 3
  max_history: 10
  max_message_length: 128
train:
  device: cpu
  batch_size: 4
  num_epochs: 3
  train_dataset_proportion: 0.95
  learning_rate: 6.25e-5
  lm_coeff: 2.0
  mc_coeff: 1.0
  max_norm: 1
  save_interval_mins: 15
  evaluate_interval_iters: 4000
  num_tests: 100
eval:
  model_path: checkpoints/model-20-12-22-13-00-17-iter14321.pt
  temperature: 0.7
  top_p: 0.9
bot:
  bot_token: TOKEN_HERE
  history_limit: 10
  token_limit: 40
  max_token_history: 200
  device: cuda
  update_status_interval_mins: 15
